INSERT INTO word_types (id, name) VALUES (1, 'verb');
INSERT INTO word_types (id, name) VALUES (2, 'noun');
INSERT INTO word_types (id, name) VALUES (3, 'adjective');
INSERT INTO word_cases (id, name, word_type_id, case_order) VALUES (1, 'imperative',1, 2);
INSERT INTO word_cases (id, name, word_type_id, case_order) VALUES (2, 'infinitive',1, 1);
INSERT INTO word_cases (id, name, word_type_id, case_order) VALUES (3, 'present tense',1, 3);
INSERT INTO word_cases (id, name, word_type_id, case_order) VALUES (4, 'past tense',1, 4);
INSERT INTO word_cases (id, name, word_type_id, case_order) VALUES (5, 'supine',1, 5);
INSERT INTO word_cases (id, name, word_type_id, case_order) VALUES (6, 'indefinite singular',2, 1);
INSERT INTO word_cases (id, name, word_type_id, case_order) VALUES (7, 'definite singular',2, 2);
INSERT INTO word_cases (id, name, word_type_id, case_order) VALUES (8, 'indefinite plural',2, 3);
INSERT INTO word_cases (id, name, word_type_id, case_order) VALUES (9, 'definite plural',2, 4);
INSERT INTO word_cases (id, name, word_type_id, case_order) VALUES (10, 'en-conjugation',3, 1);
INSERT INTO word_cases (id, name, word_type_id, case_order) VALUES (11, 'ett-conjugation',3, 2);
INSERT INTO word_cases (id, name, word_type_id, case_order) VALUES (12, 'definite and plural',3, 3);
INSERT INTO word_cases (id, name, word_type_id, case_order) VALUES (13, 'plural (irregular)',3, 4);
INSERT INTO languages (id, name, translation_order) VALUES (1, 'German', 10);
INSERT INTO languages (id, name, translation_order) VALUES (2, 'Swedish', 20);
INSERT INTO lectures (id, name) VALUES (1, 'A1, L1');
INSERT INTO lectures (id, name) VALUES (2, 'A1, L2');
