INSERT INTO word_types (id, name) VALUES (1, 'verb');
INSERT INTO word_types (id, name) VALUES (2, 'noun');
INSERT INTO word_types (id, name) VALUES (3, 'adjective');
INSERT INTO word_types (id, name) VALUES (6, 'numbers');
INSERT INTO word_types (id, name) VALUES (5, 'countries');
INSERT INTO word_types (id, name) VALUES (4, 'no_type');
INSERT INTO languages (id, name, translation_order) VALUES (1, 'German', 10);
INSERT INTO languages (id, name, translation_order) VALUES (2, 'Swedish', 20);
INSERT INTO word_cases (id, name, word_type_id, language_id, case_order) VALUES (1, 'imperative', 1, 2, 50);
INSERT INTO word_cases (id, name, word_type_id, language_id, case_order) VALUES (2, 'infinitive', 1, 2, 10);
INSERT INTO word_cases (id, name, word_type_id, language_id, case_order) VALUES (3, 'present tense', 1, 2, 20);
INSERT INTO word_cases (id, name, word_type_id, language_id, case_order) VALUES (4, 'past tense', 1, 2, 30);
INSERT INTO word_cases (id, name, word_type_id, language_id, case_order) VALUES (5, 'supine', 1, 2, 40);
INSERT INTO word_cases (id, name, word_type_id, language_id, case_order) VALUES (6, 'indefinite singular', 2, 2, 10);
INSERT INTO word_cases (id, name, word_type_id, language_id, case_order) VALUES (7, 'definite singular', 2, 2, 20);
INSERT INTO word_cases (id, name, word_type_id, language_id, case_order) VALUES (8, 'indefinite plural', 2, 2, 30);
INSERT INTO word_cases (id, name, word_type_id, language_id, case_order) VALUES (9, 'definite plural', 2, 2, 40);
INSERT INTO word_cases (id, name, word_type_id, language_id, case_order) VALUES (10, 'en-conjugation', 3, 2, 10);
INSERT INTO word_cases (id, name, word_type_id, language_id, case_order) VALUES (11, 'ett-conjugation', 3, 2, 20);
INSERT INTO word_cases (id, name, word_type_id, language_id, case_order) VALUES (12, 'definite and plural', 3, 2, 30);
INSERT INTO word_cases (id, name, word_type_id, language_id, case_order) VALUES (13, 'plural (irregular)', 3, 2, 40);
INSERT INTO word_cases (id, name, word_type_id, language_id, case_order) VALUES (14, 'infinitive', 1, 1, 10);
INSERT INTO word_cases (id, name, word_type_id, language_id, case_order) VALUES (15, 'definite singular', 2, 1, 20);
INSERT INTO word_cases (id, name, word_type_id, language_id, case_order) VALUES (16, 'singular', 3, 1, 10);
INSERT INTO word_cases (id, name, word_type_id, language_id, case_order) VALUES (17, 'none', 4, 1, 10);
INSERT INTO word_cases (id, name, word_type_id, language_id, case_order) VALUES (18, 'none', 5, 1, 10);
INSERT INTO word_cases (id, name, word_type_id, language_id, case_order) VALUES (19, 'none', 6, 1, 10);
INSERT INTO word_cases (id, name, word_type_id, language_id, case_order) VALUES (20, 'translation', 4, 2, 10);
INSERT INTO word_cases (id, name, word_type_id, language_id, case_order) VALUES (21, 'indefinite singular', 5, 2, 10);
INSERT INTO word_cases (id, name, word_type_id, language_id, case_order) VALUES (22, 'definite singular', 5, 2, 20);
INSERT INTO word_cases (id, name, word_type_id, language_id, case_order) VALUES (23, 'translation', 6, 2, 10);
INSERT INTO lectures (id, name) VALUES (1, 'A1L01');
INSERT INTO lectures (id, name) VALUES (2, 'A1L02');
INSERT INTO lectures (id, name) VALUES (3, 'A1L03');
INSERT INTO groups (id) VALUES (1);
